// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	http "net/http"

	mock "github.com/stretchr/testify/mock"

	uptime "github.com/jsdidierlaurent/uptime-client-go"
)

// UptimecomCheckService is an autogenerated mock type for the UptimecomCheckService type
type UptimecomCheckService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, pk
func (_m *UptimecomCheckService) Get(ctx context.Context, pk int) (*uptime.Check, *http.Response, error) {
	ret := _m.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *uptime.Check
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*uptime.Check, *http.Response, error)); ok {
		return rf(ctx, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *uptime.Check); ok {
		r0 = rf(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) *http.Response); ok {
		r1 = rf(ctx, pk)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, pk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: ctx, opt
func (_m *UptimecomCheckService) List(ctx context.Context, opt *uptime.CheckListOptions) ([]*uptime.Check, *http.Response, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*uptime.Check
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *uptime.CheckListOptions) ([]*uptime.Check, *http.Response, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uptime.CheckListOptions) []*uptime.Check); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*uptime.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uptime.CheckListOptions) *http.Response); ok {
		r1 = rf(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *uptime.CheckListOptions) error); ok {
		r2 = rf(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListAll provides a mock function with given fields: ctx, opt
func (_m *UptimecomCheckService) ListAll(ctx context.Context, opt *uptime.CheckListOptions) ([]*uptime.Check, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*uptime.Check
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uptime.CheckListOptions) ([]*uptime.Check, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uptime.CheckListOptions) []*uptime.Check); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*uptime.Check)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uptime.CheckListOptions) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUptimecomCheckService creates a new instance of UptimecomCheckService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUptimecomCheckService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UptimecomCheckService {
	mock := &UptimecomCheckService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
